services:

    loki:
        image: grafana/loki:2.8.7
        container_name: loki
        ports:
            - "3100:3100"
        command: -config.file=/etc/loki/local-config.yaml
        restart: always
        volumes:
            - ${PWD}/data/loki:/loki

    grafana:
        image: grafana/grafana:10.2.2
        container_name: grafana
        ports:
            - "3000:3000"
        entrypoint:
            - sh
            - -euc
            - |
                mkdir -p /etc/grafana/provisioning/datasources
                cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
                apiVersion: 1
                datasources:
                - name: Loki
                  type: loki
                  access: proxy 
                  orgId: 1
                  url: http://loki:3100
                  basicAuth: false
                  isDefault: true
                  version: 1
                  editable: false
                EOF
                /run.sh
        environment:
            - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
        restart: always
        volumes:
            - ${PWD}/data/grafana:/var/lib/grafana
